# Generated by Django 3.1.3 on 2022-06-07 13:22

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Font_keyword_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=50)),
                ('key_value', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
